/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    agentes: Agente;
    clientes: Cliente;
    'listado-agentes-propiedades': ListadoAgentesPropiedade;
    propiedades: Propiedade;
    transacciones: Transaccione;
    referidos: Referido;
    visitas: Visita;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    agentes: AgentesSelect<false> | AgentesSelect<true>;
    clientes: ClientesSelect<false> | ClientesSelect<true>;
    'listado-agentes-propiedades': ListadoAgentesPropiedadesSelect<false> | ListadoAgentesPropiedadesSelect<true>;
    propiedades: PropiedadesSelect<false> | PropiedadesSelect<true>;
    transacciones: TransaccionesSelect<false> | TransaccionesSelect<true>;
    referidos: ReferidosSelect<false> | ReferidosSelect<true>;
    visitas: VisitasSelect<false> | VisitasSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'agente' | 'cliente';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agentes".
 */
export interface Agente {
  id: number;
  nombre: string;
  apellido: string;
  email: string;
  telefono?: string | null;
  comision?: number | null;
  referral_code: string;
  fecha_contratacion?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clientes".
 */
export interface Cliente {
  id: number;
  nombre: string;
  apellido: string;
  email: string;
  telefono?: string | null;
  tipo: 'propietario' | 'comprador' | 'arrendatario';
  preferencias?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  fecha_registro?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listado-agentes-propiedades".
 */
export interface ListadoAgentesPropiedade {
  id: number;
  agente: number | Agente;
  propiedad: number | Propiedade;
  fecha_envio?: string | null;
  enlace_generado: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "propiedades".
 */
export interface Propiedade {
  id: number;
  titulo: string;
  direccion: string;
  ciudad: string;
  pais: string;
  /**
   * @minItems 2
   * @maxItems 2
   */
  ubicacion?: [number, number] | null;
  tipo: 'venta' | 'alquiler';
  precio: number;
  moneda?: string | null;
  metros_cuadrados?: number | null;
  habitaciones?: number | null;
  baños?: number | null;
  caracteristicas?: ('estacionamiento' | 'piscina' | 'jardin' | 'garaje')[] | null;
  descripcion?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  estado: 'disponible' | 'reservada' | 'vendida' | 'alquilada';
  fecha_publicacion?: string | null;
  fecha_actualizacion?: string | null;
  propietario?: (number | null) | Cliente;
  agente?: (number | null) | Agente;
  imagenes?:
    | {
        imagen?: (number | null) | Media;
        descripcion_imagen?: string | null;
        id?: string | null;
      }[]
    | null;
  destacada?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transacciones".
 */
export interface Transaccione {
  id: number;
  propiedad: number | Propiedade;
  cliente?: (number | null) | Cliente;
  agente?: (number | null) | Agente;
  tipo: 'venta' | 'alquiler';
  monto: number;
  fecha_transaccion?: string | null;
  estado: 'pendiente' | 'completada' | 'cancelada';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "referidos".
 */
export interface Referido {
  id: number;
  agente: number | Agente;
  cliente: number | Cliente;
  referral_code: string;
  fecha_referido?: string | null;
  origen?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visitas".
 */
export interface Visita {
  id: number;
  propiedad: number | Propiedade;
  cliente?: (number | null) | Cliente;
  agente?: (number | null) | Agente;
  fecha_visita: string;
  estado: 'programada' | 'realizada' | 'cancelada';
  comentarios?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'agentes';
        value: number | Agente;
      } | null)
    | ({
        relationTo: 'clientes';
        value: number | Cliente;
      } | null)
    | ({
        relationTo: 'listado-agentes-propiedades';
        value: number | ListadoAgentesPropiedade;
      } | null)
    | ({
        relationTo: 'propiedades';
        value: number | Propiedade;
      } | null)
    | ({
        relationTo: 'transacciones';
        value: number | Transaccione;
      } | null)
    | ({
        relationTo: 'referidos';
        value: number | Referido;
      } | null)
    | ({
        relationTo: 'visitas';
        value: number | Visita;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agentes_select".
 */
export interface AgentesSelect<T extends boolean = true> {
  nombre?: T;
  apellido?: T;
  email?: T;
  telefono?: T;
  comision?: T;
  referral_code?: T;
  fecha_contratacion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clientes_select".
 */
export interface ClientesSelect<T extends boolean = true> {
  nombre?: T;
  apellido?: T;
  email?: T;
  telefono?: T;
  tipo?: T;
  preferencias?: T;
  fecha_registro?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listado-agentes-propiedades_select".
 */
export interface ListadoAgentesPropiedadesSelect<T extends boolean = true> {
  agente?: T;
  propiedad?: T;
  fecha_envio?: T;
  enlace_generado?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "propiedades_select".
 */
export interface PropiedadesSelect<T extends boolean = true> {
  titulo?: T;
  direccion?: T;
  ciudad?: T;
  pais?: T;
  ubicacion?: T;
  tipo?: T;
  precio?: T;
  moneda?: T;
  metros_cuadrados?: T;
  habitaciones?: T;
  baños?: T;
  caracteristicas?: T;
  descripcion?: T;
  estado?: T;
  fecha_publicacion?: T;
  fecha_actualizacion?: T;
  propietario?: T;
  agente?: T;
  imagenes?:
    | T
    | {
        imagen?: T;
        descripcion_imagen?: T;
        id?: T;
      };
  destacada?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transacciones_select".
 */
export interface TransaccionesSelect<T extends boolean = true> {
  propiedad?: T;
  cliente?: T;
  agente?: T;
  tipo?: T;
  monto?: T;
  fecha_transaccion?: T;
  estado?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "referidos_select".
 */
export interface ReferidosSelect<T extends boolean = true> {
  agente?: T;
  cliente?: T;
  referral_code?: T;
  fecha_referido?: T;
  origen?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visitas_select".
 */
export interface VisitasSelect<T extends boolean = true> {
  propiedad?: T;
  cliente?: T;
  agente?: T;
  fecha_visita?: T;
  estado?: T;
  comentarios?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}